In [1]:
import tensorflow as tf

In [2]:
#Creating Random Tensor
tensor_1 =  tf.random.Generator.from_seed(42)
tensor_1 = tf.random.normal(shape=(3,2))
tensor_2 = tf.random.Generator.from_seed(42)
tensor_2 = tf.random.normal(shape=(3,2))

tensor_1 , tensor_2, tensor_1 == tensor_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.497541  , -0.1563365 ],
        [ 0.75642914, -0.8366591 ],
        [ 0.1207549 ,  0.17000541]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.4194767 ,  2.5528476 ],
        [ 0.8231884 , -0.08736406],
        [ 1.1672938 , -1.4381962 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [3]:
#shuffle the tensor (it when need you want the shuffle the tensor)
not_shuffle = tf.constant([[10,7],
                           [2,8],
                           [7,9]])
not_shuffle.ndim


2

In [4]:
not_shuffle


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  8],
       [ 7,  9]], dtype=int32)>

In [5]:
#shuffle The Tensor
tf.random.shuffle(not_shuffle)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  8],
       [ 7,  9],
       [10,  7]], dtype=int32)>

In [6]:
tf.random.shuffle(not_shuffle, seed = 42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  9],
       [ 2,  8],
       [10,  7]], dtype=int32)>

In [7]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffle, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  8],
       [ 7,  9]], dtype=int32)>

Numpy to Tensor


In [8]:
#create The Numpy arrays
import numpy as np
numpy_A = np.ones([7,8])
numpy_A



array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
numpy_B = np.zeros(shape=([5,7]))
numpy_B

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [10]:
tf.constant(numpy_A)

<tf.Tensor: shape=(7, 8), dtype=float64, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])>

In [11]:
#Numpy to tensor
A = np.arange(1,25, dtype = np.int32)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [12]:
tf.constant(A , shape=(2,3,4))
# tf.constant(matrix) # capital for vector and tensor
# tf.constant(Vector) # non-capital for vector

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [13]:
A = tf.constant(A , shape=(3,8))
B = tf.constant (A)
A ,B


(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

getting information from your tensor

In [14]:
#Create a 4 diamensien tensor
rank_tensor = tf.zeros(shape= (2,3,4,5))
rank_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [15]:
print("Datatype odf every tensor ", rank_tensor.dtype)
print ("Number of Diamension of the tensor ", rank_tensor.ndim)
print("Datatype odf every tensor ", rank_tensor.dtype)
print ("Number of Diamension of the tensor ", rank_tensor.ndim)
print("Shape of the tensor", rank_tensor.shape)
print("Elememts along the First Axis ", rank_tensor.shape[0])
print("Elemernts alog the Last Axis ",rank_tensor.shape[-1])
print("Total Number of the element in our  tensor  ", tf.size(rank_tensor))
print ("total numner of the element in  our tensor ", tf.size(rank_tensor).numpy())

Datatype odf every tensor  <dtype: 'float32'>
Number of Diamension of the tensor  4
Datatype odf every tensor  <dtype: 'float32'>
Number of Diamension of the tensor  4
Shape of the tensor (2, 3, 4, 5)
Elememts along the First Axis  2
Elemernts alog the Last Axis  5
Total Number of the element in our  tensor   tf.Tensor(120, shape=(), dtype=int32)
total numner of the element in  our tensor  120


Indexing

In [16]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [17]:
rank_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [18]:
some_list[:1]

[1]

In [19]:
rank_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [20]:
rank_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [21]:
rank_tensor[:, :1 ,:1 ,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [22]:
rank_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [23]:
rank_tensor[:1,:,:1,:]

<tf.Tensor: shape=(1, 3, 1, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
#Creatig rank_2 Tensor
rank_2_tensor = tf.constant([[10,7],
                             [12,13]])
rank_2_tensor.shape , rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [25]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [26]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [12, 13]], dtype=int32)>

In [27]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 13], dtype=int32)>

In [28]:
rank_2_tensor[:1, :]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10,  7]], dtype=int32)>

In [29]:
#Adding 3 tensor use the tf.addaxis
another_rank_tensor = rank_2_tensor[...,tf.newaxis]
# another_ranbK_tensor = rank_2_tensor[:,:, tf,newaxis]

In [30]:
another_rank_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[12],
        [13]]], dtype=int32)>

In [31]:
#Alterntive tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # expand the final tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[12],
        [13]]], dtype=int32)>

In [32]:
tf.expand_dims(rank_2_tensor, axis=0) #expand the first tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [12, 13]]], dtype=int32)>

Matrix multification also refffered as the Dot product
You can perform matrix multification using
tf.matmul()
tf.tensordot()'

In [33]:
x , y

NameError: name 'x' is not defined