
Matrix Multification
In Machine Learning Matrix Multification one of the most common tensor  operation
There Are Two RuLes our Tensors( Or metrics) need to fullfill if are going to matrix multify them
1.The Inner diamenion Must match
2.The resulting matrix has the shape of the inner diamensiom

In [4]:
import tensorflow as tf

In [5]:
tensor = tf.constant([[10,7],
                      [3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [6]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [7]:
tensor,tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [8]:
# Matrix multification in Python
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [9]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [10]:
# Creating [3,2] matrix
x = tf.constant([[1,2],
                 [2,4],
                 [6,8]])
y = tf.constant([[2,3],
                 [5,7],
                 [1,9]])

In [11]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 4],
        [6, 8]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 3],
        [5, 7],
        [1, 9]], dtype=int32)>)

In [12]:
x @ y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [13]:
tf.matmul(x,y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [14]:
# lets change the Y shape
tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 5],
       [7, 1, 9]], dtype=int32)>

In [15]:
x.shape , tf.reshape(y, shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [16]:
x @ tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 16,   5,  23],
       [ 32,  10,  46],
       [ 68,  26, 102]], dtype=int32)>

In [17]:
x.shape ,tf.reshape(x, shape=(2,3)).shape , y.shape


(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([3, 2]))

In [18]:
 # Change The Shape of the X Metrics and multification-
 tf.reshape(x, shape=(2,3)) @ y


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 14,  35],
       [ 46, 126]], dtype=int32)>

In [19]:
tf.matmul(tf.reshape(x, shape=(2,3)), y)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 14,  35],
       [ 46, 126]], dtype=int32)>

In [20]:
# Now Use transpose
x,tf.transpose(x)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 4],
        [6, 8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 6],
        [2, 4, 8]], dtype=int32)>)

In [21]:
tf.transpose(x)@ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 18,  71],
       [ 32, 106]], dtype=int32)>

In [22]:
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 18,  71],
       [ 32, 106]], dtype=int32)>

In [23]:
x, y


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 4],
        [6, 8]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 3],
        [5, 7],
        [1, 9]], dtype=int32)>)

In [28]:
tf.tensordot(  x , tf.transpose(y), axes =1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 8, 19, 19],
       [16, 38, 38],
       [36, 86, 78]], dtype=int32)>

In [31]:
tf.tensordot(x, tf.reshape(y , shape=(2,3)), axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 16,   5,  23],
       [ 32,  10,  46],
       [ 68,  26, 102]], dtype=int32)>

In [33]:
 tf.matmul(x , tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 8, 19, 19],
       [16, 38, 38],
       [36, 86, 78]], dtype=int32)>

In [35]:
tf.matmul(x, tf.reshape(y , shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 16,   5,  23],
       [ 32,  10,  46],
       [ 68,  26, 102]], dtype=int32)>

In [36]:
tf.tensordot(tf.transpose(x),y , axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 18,  71],
       [ 32, 106]], dtype=int32)>

In [41]:
tf.tensordot(tf.reshape(x , shape=(2,3)),y,axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 14,  35],
       [ 46, 126]], dtype=int32)>

In [50]:
# The Information about the metrics
print('Normal Y :--------------')
print('\n', y)
print('Reshape Multification X: -------------')
print('\n', tf.matmul(tf.reshape(x, shape=(2,3)),y))
print('Transpose Multification X:-------------')
print('\n', tf.matmul(tf.transpose(x),y))
print('Reshape Multification Y :-------')
print('\n', tf.matmul(x, tf.reshape(y, shape=(2,3))))

print('Transpose Multification Y :----------------')
print('\n',tf.matmul(x, tf.transpose(y)))



Normal Y :--------------

 tf.Tensor(
[[2 3]
 [5 7]
 [1 9]], shape=(3, 2), dtype=int32)
Reshape Multification X: -------------

 tf.Tensor(
[[ 14  35]
 [ 46 126]], shape=(2, 2), dtype=int32)
Transpose Multification X:-------------

 tf.Tensor(
[[ 18  71]
 [ 32 106]], shape=(2, 2), dtype=int32)
Reshape Multification Y :-------

 tf.Tensor(
[[ 16   5  23]
 [ 32  10  46]
 [ 68  26 102]], shape=(3, 3), dtype=int32)
Transpose Multification Y :----------------

 tf.Tensor(
[[ 8 19 19]
 [16 38 38]
 [36 86 78]], shape=(3, 3), dtype=int32)
