In [2]:
# Importing Tensorflow
import tensorflow as tf
print(tf.__version__)

2.17.0


In [3]:
#create Tensor with tf.constant()
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#Check The Number Of Diamension Of the scaler .(ndim stand for number of diamension)
scaler.ndim


0

In [6]:
# Crete A Vector
vector = tf.constant([10 , 2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  2], dtype=int32)>

In [7]:
#Number Diamenion of vector
vector.ndim

1

In [9]:
#Create A Matrix (Matrix Is Minimum 2 daimensional )
matrix = tf.constant([[10,7],
                     [12,13]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [12, 13]], dtype=int32)>

In [10]:
# Number of diamension of matrix
matrix.ndim

2

In [12]:
#Create Another matrix
another_matrix = tf.constant([[100,200],
                              [400,500],
                              [400,800]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[100., 200.],
       [400., 500.],
       [400., 800.]], dtype=float16)>

In [15]:
#Crerate A tensor
tensor = tf.constant([[[10,20,30],
                       [40,50,60]],
                      [[20,30,40],
                       [20,30,40]],
                      [[50,60,70],
                       [90,80,70]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[10, 20, 30],
        [40, 50, 60]],

       [[20, 30, 40],
        [20, 30, 40]],

       [[50, 60, 70],
        [90, 80, 70]]], dtype=int32)>

In [16]:
#Number of diamension of tensor
tensor.ndim

3